# Generated by Django 4.2.4 on 2023-08-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="transcript",
            field=models.TextField(blank=True),
        ),
    ]
