# Generated by Django 4.2.4 on 2023-08-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0002_alter_conversation_transcript"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="duration",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
