# Generated by Django 4.2.4 on 2023-08-17 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0006_alter_dialog_options_conversation_dialog_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="dialog_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="conversations.dialog"
            ),
        ),
    ]
