# Generated by Django 4.2.4 on 2023-08-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0007_alter_conversation_dialog_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="transcript",
        ),
        migrations.AddField(
            model_name="conversation",
            name="speaker_type",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
