# Generated by Django 4.2.4 on 2023-08-17 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0009_remove_conversation_user_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="transcript",
            field=models.TextField(blank=True),
        ),
    ]
