# Generated by Django 4.2.4 on 2023-08-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0010_conversation_transcript"),
    ]

    operations = [
        migrations.AddField(
            model_name="dialog",
            name="state",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
