# Generated by Django 4.2.4 on 2023-08-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0011_dialog_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dialog",
            name="state",
            field=models.CharField(default="CLOSED", max_length=100),
        ),
    ]
