# Generated by Django 4.2.4 on 2023-09-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0012_alter_dialog_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="duration",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
